import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import Editor from "@monaco-editor/react";
import "./App.css";

function registerLatexLanguage(monaco) {
    monaco.languages.register({ id: "latex" });
    monaco.languages.setMonarchTokensProvider("latex", {
        tokenizer: {
            root: [
                [/%.*$/, "comment"],
                [/\\[a-zA-Z@]+/, "keyword"],
                [/\{|\}/, "delimiter.bracket"],
                [/\$+/, "delimiter"],
                [/\\begin(?=\{)/, "keyword"],
                [/\\end(?=\{)/, "keyword"]
            ]
        }
    });
    monaco.languages.setLanguageConfiguration("latex", {
        comments: { lineComment: "%" },
        brackets: [
            ["{", "}"],
            ["[", "]"],
            ["(", ")"]
        ],
        autoClosingPairs: [
            { open: "{", close: "}" },
            { open: "[", close: "]" },
            { open: "(", close: ")" },
            { open: "$", close: "$" }
        ],
        surroundingPairs: [
            { open: "{", close: "}" },
            { open: "[", close: "]" },
            { open: "(", close: ")" },
            { open: "$", close: "$" }
        ]
    });
}

function App() {
    // 默认的 LaTeX 模版代码
    const [code, setCode] = useState(
        `\\documentclass{article}
\\usepackage{amsmath}
\\begin{document}
\\title{Hello Tauri + Tectonic}
\\author{Your Name}
\\maketitle

\\section{Introduction}
This is a \\textbf{PDF} generated by Tectonic via CLI!

\\section{Formula}
Einstein said:
$$ E = mc^2 $$

\\end{document}`
    );

    const [pdfUrl, setPdfUrl] = useState("");
    const [loading, setLoading] = useState(false);
    const [logs, setLogs] = useState("");

    async function handleCompile() {
        setLoading(true);
        setLogs("Compiling... (Check terminal for details)");
        try {
            // 调用我们在 Rust 后端写的 compile_latex 命令
            const pdfBytes = await invoke("compile_latex", { latexCode: code });

            // 将返回的二进制数据转换为可以在浏览器显示的 URL
            const byteArray = new Uint8Array(pdfBytes);
            const blob = new Blob([byteArray], { type: "application/pdf" });
            const url = URL.createObjectURL(blob);

            setPdfUrl(url);
            setLogs("Success! PDF generated.");
        } catch (e) {
            console.error(e);
            setLogs("Error: " + e);
            alert("编译出错: " + e);
        } finally {
            setLoading(false);
        }
    }

    return (
        <div style={{ display: "flex", height: "100vh", flexDirection: "column", fontFamily: "sans-serif" }}>
            {/* 顶部工具栏 */}
            <div style={{ padding: "10px", background: "#f0f0f0", borderBottom: "1px solid #ccc", display: "flex", alignItems: "center", gap: "10px" }}>
                <button
                    onClick={handleCompile}
                    disabled={loading}
                    style={{ padding: "8px 16px", cursor: loading ? "not-allowed" : "pointer", backgroundColor: "#007acc", color: "white", border: "none", borderRadius: "4px" }}
                >
                    {loading ? "Compiling..." : "▶ Run Compile"}
                </button>
                <span style={{ fontSize: "12px", color: loading ? "blue" : "#333" }}>{logs}</span>
            </div>

            {/* 主体区域 */}
            <div style={{ display: "flex", flex: 1, overflow: "hidden" }}>
                {/* 左侧：编辑器 */}
                <div style={{ width: "50%", borderRight: "1px solid #ddd" }}>
                    <Editor
                        height="100%"
                        language="latex"
                        theme="vs-dark"
                        value={code}
                        onChange={(value) => setCode(value || "")}
                        beforeMount={registerLatexLanguage}
                        options={{
                            minimap: { enabled: false },
                            fontSize: 14,
                            wordWrap: "on"
                        }}
                    />
                </div>

                {/* 右侧：预览 */}
                <div style={{ width: "50%", background: "#555", display: "flex", alignItems: "center", justifyContent: "center" }}>
                    {pdfUrl ? (
                        <iframe
                            src={pdfUrl}
                            width="100%"
                            height="100%"
                            style={{ border: "none" }}
                            title="PDF Preview"
                        />
                    ) : (
                        <div style={{ color: "#ccc" }}>Click "Run Compile" to generate PDF</div>
                    )}
                </div>
            </div>
        </div>
    );
}

export default App;
